Escolar32/Controllers/BairrosController.cs
using Escolar32.Context;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Escolar32.Controllers
{

    public class BairrosController : Controller
    {
        private readonly AppDbContext _context;

        public BairrosController(AppDbContext context)
        {
            _context = context;
        }
        public async Task<IActionResult> Bairros()
        {
            return View(await _context.Bairros.ToListAsync());
        }
    }
}

Escolar32/Controllers/EscolasController.cs
using Microsoft.AspNetCore.Mvc;

namespace Escolar32.Controllers
{
    public class EscolasController : Controller
    {
        public IActionResult Escolas()
        {
            return View();
        }
    }
}

Escolar32/Controllers/FotosController.cs
using Escolar32.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Options;

namespace Escolar32.Controllers
{
    public class FotosController : Controller
    {
        private readonly ConfigurationImagens _myConfig;

        private readonly IWebHostEnvironment _hostingEnvironment;
        public FotosController(IWebHostEnvironment hostingEnvironment,
            IOptions<ConfigurationImagens> myConfiguration)
        {
            _hostingEnvironment = hostingEnvironment;
            _myConfig = myConfiguration.Value;
        }

        public IActionResult Fotos()
        {
            FileManagerModel model = new FileManagerModel();

            var userImagesPath = Path.Combine(_hostingEnvironment.WebRootPath,
                 _myConfig.NomePastaImagensProdutos);

            DirectoryInfo dir = new DirectoryInfo(userImagesPath);
            FileInfo[] files = dir.GetFiles();
            model.PathImagesProduto = _myConfig.NomePastaImagensProdutos;

            if (files.Length == 0)
            {
                ViewData["Erro"] = $"Nenhum arquivo encontrado na pasta {userImagesPath}";
            }

            model.Files = files;
            return View(model);
        }
    }

}

Escolar32/Views/Shared/_Footer.cshtml
<footer>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow mb-0">
        <div class="container">
            <div class="row align-items-center footer">
                <div class="col-sm-4" style="color: white">
                    <h4 class="frase">Professores ensinam, pais educam, nós transportamos!</h4>
                </div>
                <div class="col-sm-3 footer" style="color: white">
                    <span>
                        <img src="/Imagens/phone-app-icon.png" />
                    </span>
                    <p class="py-1"> (13) 99184-6502</p>
                </div>
                <div class="col-sm-3 footer" style="color: white">
                    <span>
                        <img src="~/Imagens/Envelope-icon24.png" />
                    </span>
                   <p class="py-1"> <a href="mailto:escolar32sv@gmail.com" 
                   style="color: yellow">escolar32sv@gmail.com</a></p>
                </div>
                <div class="col-sm-2" style="color: white">
                    <p> &copy; 2023 - Escolar 32</p>
                </div>
            </div>
        </div>
    </nav>
</footer>

Escolar32/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] Escolar 32 </title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Escolar32.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/lib/font-awesome/css/all.css" />
    <link rel="shortcut icon" href="~/transporte.jpg">
    
    
</head>
<body class="row">
    <header>
        <div class="topo container-fluid ">
            <a class="whats" href="http://api.whatsapp.com/send?1=pt_BR&amp;phone=5513991846502" target=" _blank">
                <img src="~/imagens/whatsapp.png" width="60">
                <br />Orçamento
            </a>
            <h1 class="h1">E &nbsp;S&nbsp; C&nbsp; O&nbsp; L&nbsp; A&nbsp; R&nbsp;&nbsp;   3&nbsp; 2</h1>
        </div>
        <nav class="navbar navbar-expand-sm navbar-dark bg-dark">
            <div class="container-fluid">
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navegacao" 
                        aria-controls="navegacao" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navegacao">

                    <ul class="navbar-nav col justify-content-center">

                        <li class="nav-item me-sm-5">
                            <a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="Home">Home</a>
                        </li>
                        <li class="nav-item me-sm-5">
                            <a class="nav-link text-white" asp-area="" asp-controller="Escolas" asp-action="Escolas">Escolas</a>
                        </li>
                        <li class="nav-item me-sm-5">
                            <a class="nav-link text-white" asp-area="" asp-controller="Bairros" asp-action="Bairros">Bairros</a>
                        </li>
                        <li class="nav-item me-sm-5">
                            <a class="nav-link text-white" asp-area="" asp-controller="Fotos" asp-action="Fotos">Fotos</a>
                        </li>
                    </ul>
                    
                    @await Html.PartialAsync("_LoginPartial")
                    @if (User.IsInRole("Admin"))
                    {
                        <a class="nav-link text-light" asp-area="Admin" asp-controller="Admin" asp-action="Index">Admin</a>
                    }
                    @if (User.IsInRole("Member"))
                    {
                        <a class="nav-link text-light" asp-area="Usuario" asp-controller="Home" asp-action="Aluno">Usuário</a>
                    }
                </div>
            </div>
        </nav>
    </header>
    <div class="container mb-0">
        <main role="main">
            @RenderBody()
        </main>
    </div>

    <partial name="_Footer" />

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>